name: Deply de la pagina
on:
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-om: ubuntu-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2.3.1

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deplay-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deplay to.
        folder: .  # The folder the action should deplay.